player:
  position:
    location: cell
    next location: ''
    last room: Entrance
  inventory: []
  stats:
    health: 20
    attack: 2

rooms:
  cell:
    messages:
      description: |
        You find yourself in a jail cell with the door locked.
        As you look outside the bars, you can see a corridor extending in
        either direction. For now, you need to get out of here. upon further
        inspection in the room, you note various shackles and torture
        instruments, a metal bed suspended from the wall with a chain, but
        nothing more.
      inspect: |
        upon checking under the bed, you find a key. How convenient
        for you, prisoner!
      unlock message: ""
    door: 
      locked: False
      unlock: ''
      item: ['key', 'skull']
    fight:
      fight: False
      enemy: ''
    paths:
      up: 'Jail hallway'
      down: ''
      left: ''
      right: ''

  Jail hallway:
    messages:
      description: |
        A long, narrow hallway lined with cells and torches for light on
        either side. To your immediate left, there is a crumbling wall.
        Perhaps if you had something that could help destroy it...
        To your right, down the corridor, there is a stairwell. The stairs
        lead up, but it is completely pitch black inside. You'll probably
        trip and hurt yourself without a source of light. You should be
        able to reach up and remove one of the torches from the wall.
      inspect: 'You inspect the room'
      unlock message: "You have unlocked the door but the key broke."
    door:
      locked: True
      unlock: 'key'
      item: ['torch']
    fight:
      fight: True
      enemy: 'guard'
    paths:
      up: ''
      down: 'cell'
      left: 'Jail Armory'
      right: 'Stairwell'

  Stairwell:
    messages:
      description: |
        The stairs are falling apart as you carefully watch your footing and
        traverse the stairs. Looking down the stairs you know they will lead
        you back to the hallway but going up will take you to the tower.
      inspect: 'You inspect the room'
      unlock message: |
        The torch lights your way allowing you to enter the dark
        and crumbling stairwell.
    door:
      locked: True
      unlock: 'torch'
      item: ['brick']
    fight:
      fight: False
      enemy: ''
    paths:
      up: 'Jail Tower'
      down: 'Jail hallway'
      left: 'Jail hallway'
      right: ''

  Jail Tower:
    messages:
      description: |
        As you exit the stairwell and go outside, you find yourself atop a
        tower. It is raining hard and a storm is currently ongoing. You
        hear the sounds of thunder and see bright flashes of lightning
        every now and then. As you look over the edge of the tower,
        you see nothing but a raging ocean.
      inspect: |
        As you look around on top of the tower, you note that
        there is a bar leaned up against the wall, near the door you
        emerged from. 
      unlock message: ""
    door:
      locked: False
      unlock: ''
      item: ['bar']
    fight:
      fight: True
      enemy: 'guard'
    paths:
      up: ''
      down: 'Stairwell'
      left: ''
      right: ''

  Jail Armory:
    messages:
      description: |
        You enter the armory and note that the armor and weapon
        racks are all but empty. You also note the presence of a few target
        dummies and archery targets. In front of you is a door which
        is cracked open. Looking through you can see a giant of a man
        standing in the middle of the room.
      inspect: |
        One of the dummies has a sword embedded in it. You are able
        to pull the sword from the dummy with a little effort.
      unlock message: "You break down the crumbling wall with the iron bar but the bar doesn't look to good."
    door:
      locked: True
      unlock: 'bar'
      item: ['sword']
    fight:
      fight: True
      enemy: 'guard'
    paths:
      up: 'Boss room'
      down: ''
      left: ''
      right: 'Jail hallway'

  Boss room:
    messages:
      description: |
        You enter the room having to step around the corpse of the man.
        To your left you see a large gated door with what looks like
        gold bars on the other side and in front of you, and behind
        the man looks to be a door to the outside.
      inspect: 'You see a painting that you could probably take'
      unlock message: "Using the sword you fight and beat the man."
    door:
      locked: True
      unlock: 'sword'
      item: ['painting']
    fight:
      fight: True
      enemy: 'boss'
    paths:
      up: 'Entrance'
      down: 'Jail Armory'
      left: 'Vault'
      right: ''

  Vault:
    messages:
      description: |
        You have entered the vault. All around you is gold, silver, and
        bronze coins which could help you if you find the exit to this place.
      inspect: 'You see the coins all around the room.'
      unlock message: ""
    door:
      locked: False
      unlock: ''
      item: ['coins']
    fight:
      fight: False
      enemy: ''
    paths:
      up: ''
      down: ''
      left: ''
      right: 'Boss room'

  Entrance:
    messages:
      description: |
        It seems that you have left the prison. 
      inspect: ''
      unlock message: ""
    door:
      locked: False
      unlock: ''
      item: []
    fight:
      fight: False
      enemy: ''
    paths:
      up: ''
      down: ''
      left: ''
      right: ''

items:
  key:
    description: "Its a cell key"
    damage: 0
  skull:
    description: "Is this Bob?"
    damage: 1
  brick:
    description: "Part of the broken stair"
    damage: 2
  torch:
    description: "It is hot"
    damage: 1
  bar:
    description: "Old rusty metal bar"
    damage: 4
  sword:
    description: "Sharp and shiny"
    damage: 5
  painting:
    description: "A painting depecting dogs playing cards"
    damage: 0
  coins:
    description: "Pretty coins, maybe i could trade these with khajiit"
    damage: 0
  
npc:
  guard:
    health: 10
    attack: 2
  boss:
    health: 20
    attack: 5